language: ruby
services: mongodb
rvm:
  - jruby
  - jruby-head
branches:
  only:
    - master
env:
  - JRUBY_OPTS="--1.8 --server -Xcext.enabled=true"
  - JRUBY_OPTS="--1.9 --server -Xcext.enabled=true"
matrix:
  include:
    - rvm: 1.8.7
      env: ''
    - rvm: 1.9.2
      env: ''
    - rvm: 1.9.3
      env: ''
    - rvm: ruby-head
      env: ''
